config/routes.rb
Todo::Application.routes.draw do
  resources :topologies

  devise_for :users  

  namespace :api, defaults: {format: :json} do
    # devise_scope :user do
    #   resource :session, only: [:create, :destroy]
    # end
    resources :task_lists, only: [:index, :create, :update, :destroy, :show] do
      resources :tasks, only: [:index, :create, :update, :destroy]
    end
  end

  devise_scope :user do
     resource :session, only: [:create, :destroy]
  end
  root :to => "templates#test"
  
  # devise_scope :user do 
  #     get '/users/sign_out' => 'sessions#new'
  # end
  get '/ajax/dashboard' => 'ajax#dashboard'
  get '/ajax/maps' => 'ajax#maps'
  get '/ajax/gallery_simple' => 'ajax#gallery_simple'
  get '/ajax/typography' => 'ajax#typography'
  get '/ajax/map_fullscreen' => 'ajax#map_fullscreen'
  get '/ajax/ui_grid' => 'ajax#ui_grid'
  get '/page_login' => 'ajax#page_login'

  get '/dashboard' => 'templates#index'
  get '/task_lists/:id' => 'templates#index'
  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/  }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list, class_name: TaskList

  acts_as_list scope: :list, column: :priority, add_new_at: :top

  validates :description, presence: true, length: {maximum: 255}
  validates :list, presence: true

  def target_priority=(value)
    insert_at(value.to_i)
  end
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  belongs_to :owner, class_name: User
  has_many :tasks, -> { order :priority }, foreign_key: :list_id, dependent: :destroy

  validates :owner, presence: true
  validates :name, presence: true
end

app/models/topology.rb
class Topology < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :token_authenticatable, :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :task_lists, foreign_key: :owner_id

  after_create :create_task_list

  def clear_authentication_token!
    update_attribute(:authentication_token, nil)
  end

  def create_task_list
    task_lists.create!(name: "My first list")
  end

  def first_list
    task_lists.first
  end
end

app/controllers/ajax_controller.rb
class AjaxController < ActionController::Base

end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  before_filter :authenticate_user!

  private

  def permission_denied
    render json: {error: 'unauthorized'}, status: :unauthorized
  end
end

app/controllers/api/sessions_controller.rb
class Api::SessionsController < Devise::SessionsController

end

app/controllers/api/task_lists_controller.rb
class Api::TaskListsController < Api::BaseController
  before_action :check_owner, only: [:show, :update, :destroy]

  def index
    render json: current_user.task_lists
  end

  def show
    render json: task_list
  end

  def create
    list = current_user.task_lists.create!(safe_params)
    render json: list
  end

  def update
    task_list.update_attributes(safe_params)
    render nothing: true
  end

  def destroy
    task_list.destroy
    render nothing: true
  end

  private
  def check_owner
    permission_denied if current_user != task_list.owner
  end

  def task_list
    @task_list ||= TaskList.find(params[:id])    
  end

  def safe_params
    params.require(:list).permit(:name)
  end
end

app/controllers/api/tasks_controller.rb
class Api::TasksController < Api::BaseController
  before_action :check_owner

  def index
    render json: task_list.tasks
  end

  def create
    task = task_list.tasks.create!(safe_params)
    render json: task, status: 201
  end

  def update
    task.update_attributes(safe_params)
    render nothing: true, status: 204
  end

  def destroy
    task.destroy
    render nothing: true, status: 204
  end

  private
  def task_list
    @task_list ||= TaskList.find(params[:task_list_id])
  end

  def task
    @task ||= task_list.tasks.find(params[:id])
  end

  def safe_params
    params.require(:task).permit(:description, :target_priority, :completed, :due_date)
  end

  def check_owner
    permission_denied if current_user != task_list.owner
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def permission_denied
    render file: "public/401.html", layout: false, status: :unauthorized
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to dashboard_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  before_action :warden_authenticate

  def create
    sign_in(resource_name, resource)
    resource.reset_authentication_token!
    flash[:notice] = "You have been signed in."
    redirect_to root_url
  end

  def destroy
    sign_out(resource_name)
    resource.clear_authentication_token!
    flash[:notice] = "You have been signed out."
    redirect_to new_user_session_path
  end

  private

  def warden_authenticate
    self.resource = warden.authenticate!(auth_options)
  end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_filter :authenticate_user!

  def index
    
  end

  def template
    render :template => 'templates/' + params[:path], :layout => nil
  end
  
end

app/controllers/topologies_controller.rb
class TopologiesController < ApplicationController
  before_action :set_topology, only: [:show, :edit, :update, :destroy]

  # GET /topologies
  # GET /topologies.json
  def index
    @topologies = Topology.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topologies }
    end
  end

  # GET /topologies/1
  # GET /topologies/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topology }
    end
  end

  # GET /topologies/new
  def new
    @topology = Topology.new
  end

  # GET /topologies/1/edit
  def edit
  end

  # POST /topologies
  # POST /topologies.json
  def create
    @topology = Topology.new(topology_params)

    respond_to do |format|
      if @topology.save
        format.html { redirect_to @topology, notice: 'Topology was successfully created.' }
        format.json { render json: @topology, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @topology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topologies/1
  # PATCH/PUT /topologies/1.json
  def update
    respond_to do |format|
      if @topology.update(topology_params)
        format.html { redirect_to @topology, notice: 'Topology was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topologies/1
  # DELETE /topologies/1.json
  def destroy
    @topology.destroy
    respond_to do |format|
      format.html { redirect_to topologies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topology
      @topology = Topology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topology_params
      params.permit(:name, :topology_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_if_current(path)
    'active' if current_page?(path)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/topologies_helper.rb
module TopologiesHelper
end

app/views/home/index.html.slim
h3 Technologies used

.panel.panel-default
  .panel-heading
    h3.panel-title Frontend

  .panel-body
    ul
      li= link_to "Bootstrap 3.0.0", "http://getbootstrap.com/"
      li= link_to "AngularJS 1.2.16", "http://angularjs.org/"
      li= link_to "jQuery 1.10.2", "http://jquery.com/"
      li= link_to "jQuery UI 1.10.3", "http://jqueryui.com/"
      li= link_to "CoffeeScript 1.6.3", "http://coffeescript.org/"
      li= link_to "Slim 2.0.1", "http://slim-lang.com/"
      li= link_to "Sass 3.2.10", "http://sass-lang.com/"
      li= link_to "Karma 0.10.2", "http://karma-runner.github.io/"
      li= link_to "Jasmine 1.3.1", "http://pivotal.github.io/jasmine/"
      li= link_to "editablespan", "https://github.com/mkwidzinska/editablespan"
      li= link_to "ui-sortable", "https://github.com/angular-ui/ui-sortable"

.panel.panel-default
  .panel-heading
    h3.panel-title Backend

  .panel-body
    ul
      li= link_to "Ruby 2.0.0p247", "http://www.ruby-lang.org/en/"
      li= link_to "Ruby on Rails 4.0.0", "http://rubyonrails.org/"
      li= link_to "Devise 3.0.3", "https://github.com/plataformatec/devise"
      li= link_to "active_model_serializers 0.8.1", "https://github.com/rails-api/active_model_serializers"
      li= link_to "acts_as_list 0.3.0", "https://github.com/swanandp/acts_as_list"
      li= link_to "Rspec 2.14", "http://rspec.info/"
      li= link_to "factory_girl 4.2.0", "https://github.com/thoughtbot/factory_girl"

h3 API

p Log in with email and password using HTTP Basic Auth. Auth token will be returned that should be used in all consecutive requests.
pre curl #{request.url}api/session -d '' -u EMAIL:PASSWORD

p List all task lists of a user.
pre curl #{request.url}api/task_lists?auth_token=TOKEN

p Create a new list
pre curl #{request.url}api/task_lists?auth_token=TOKEN -d '{"list": {"name": "New List from API"}}' -H 'Content-Type: application/json'

p Update given list
pre curl #{request.url}api/task_lists/TASK_LIST_ID?auth_token=TOKEN -d '{"list": {"name": "New name from API"}}' -H 'Content-Type: application/json' -X PATCH

p Remove given list
pre curl #{request.url}api/task_lists/TASK_LIST_ID?auth_token=TOKEN -X DELETE

p List all tasks in a given list.
pre curl #{request.url}api/task_lists/TASK_LIST_ID/tasks?auth_token=TOKEN

p Create a new task in a given list.
pre curl #{request.url}api/task_lists/TASK_LIST_ID/tasks?auth_token=TOKEN -d '{"task": {"description": "Task from API"}}' -H 'Content-Type: application/json'

p Update given task.
pre curl #{request.url}api/task_lists/TASK_LIST_ID/tasks/TASK_ID?auth_token=TOKEN -d '{"task": {"description": "New description from API"}}' -H 'Content-Type: application/json' -X PATCH

p Remove given task.
pre curl #{request.url}api/task_lists/TASK_LIST_ID/tasks/TASK_ID?auth_token=TOKEN -X DELETE

p Log out. After this action, given auth token will no longer be valid.
pre curl #{request.url}api/session?auth_token=TOKEN -X DELETE

a(href="https://github.com/mkwiatkowski/todo-rails4-angularjs" id="github-ribbon")
  img(alt="Fork me on GitHub" id="github-ribbon" src="https://s3.amazonaws.com/github/ribbons/forkme_left_green_007200.png" style="position: absolute; top: 0; left: 0; border: 0;")

app/views/layouts/_flash.html.slim
- if notice.present?
  div.alert.alert-success.alert-dismissable
    button(type="button" class="close" data-dismiss="alert" aria-hidden="true")
      ' &times
    =notice
- if alert.present?
  div.alert.alert-dismissable.alert-danger
    button(type="button" class="close" data-dismiss="alert" aria-hidden="true")
      ' &times
    = alert

app/views/layouts/_navigation.html.slim
.header
  ul.nav.nav-pills.pull-right
    - if user_signed_in?
      li
        = link_to "Log out", destroy_user_session_path, method: :delete
    - else
      li(class=active_if_current(root_path))
        = link_to "Home", root_path
      li(class=active_if_current(new_user_registration_path))
        = link_to "Sign up", new_user_registration_path
      li(class=active_if_current(new_user_session_path))
        = link_to "Sign in", new_user_session_path
  h3.text-muted
    = link_to "Todo Application", root_path

app/views/layouts/application.html.slim
doctype html
html
  head
    = tag 'meta', 'charset' => 'utf-8'
    title Todo
    = stylesheet_link_tag    "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body(ng-app="todoApp")

	= yield

app/views/templates/index.html.slim
.ng-cloak
  
  div(ng-view)  
  
    
    

app/views/templates/test.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		
		<meta name="description" content="description">
		<meta name="author" content="DevOOPS">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
		<link href='http://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
				<script src="http://getbootstrap.com/docs-assets/js/html5shiv.js"></script>
				<script src="http://getbootstrap.com/docs-assets/js/respond.min.js"></script>
		<![endif]-->
		  <title>Network | Data Manipulation</title>

  <style type="text/css">

    #mynetwork {
      position:relative;
      width: 100%;
      height: 900px;
      border: 1px solid lightgray;
      z-index: 1;
    }
    table.legend_table {
      font-size: 11px;
      border-width:1px;
      border-color:#d3d3d3;
      border-style:solid;
    }
    table.legend_table,td {
      border-width:1px;
      border-color:#d3d3d3;
      border-style:solid;
      padding: 2px;
    }
    div.table_content {
      width:80px;
      text-align:center;
    }
    div.table_description {
      width:100px;
    }

    #operation {
      font-size:28px;
    }
    #network-popUp {
      display:none;
      position:absolute;
      top:350px;
      left:170px;
      z-index:299;
      width:250px;
      height:120px;
      background-color: #f9f9f9;
      border-style:solid;
      border-width:3px;
      border-color: #5394ed;
      padding:10px;
      text-align: center;
    }
  </style>
  <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
      function initialize() {
        var map_canvas = document.getElementById('googlemaps');
        var map_options = {
          center: new google.maps.LatLng(38.013083, 22.749513),
          zoom: 10,
          disableDefaultUI: true,
           scaleControl: false,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(map_canvas, map_options)
      }
      google.maps.event.addDomListener(window, 'load', initialize);

      	var url = '/topologies.json';
				// Create a variable in JSON format
		var topology = {
		    name: 'Jeff',
		    topology_type: 'Smith' 
		}
		
		$.ajax({
		  type: "POST",
		  url: url,
		  data: topology
		});
    </script>
  
  
	</head>
<body onload="draw();">
<!--Start Header-->
<div id="screensaver">
	<canvas id="canvas"></canvas>
	<i class="fa fa-lock" id="screen_unlock"></i>
</div>
<div id="modalbox">
	<div class="devoops-modal">
		<div class="devoops-modal-header">
			<div class="modal-header-name">
				<span>Basic table</span>
			</div>
			<div class="box-icons">
				<a class="close-link">
					<i class="fa fa-times"></i>
				</a>
			</div>
		</div>
		<div class="devoops-modal-inner">
		</div>
		<div class="devoops-modal-bottom">
		</div>
	</div>
</div>
<header class="navbar">
	<div class="container-fluid expanded-panel">
		<div class="row">
			<div id="logo" class="col-xs-12 col-sm-2">
				<a href="index.html">Mantis </a>
			</div>
			<div id="top-panel" class="col-xs-12 col-sm-10">
				<div class="row">
					<div class="col-xs-8 col-sm-4">
						<a href="#" class="show-sidebar">
						  <i class="fa fa-bars"></i>
						</a>
						<div id="search">
							<input type="text" placeholder="search for projects and researchers"/>
							<i class="fa fa-search"></i>
						</div>
					</div>
					<div class="col-xs-4 col-sm-8 top-panel-right">
						<ul class="nav navbar-nav pull-right panel-menu">
							<li class="hidden-xs">
								<a href="index.html" class="modal-link">
									<i class="fa fa-bell"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="hidden-xs">
								<a class="ajax-link" href="ajax/calendar.html">
									<i class="fa fa-calendar"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="hidden-xs">
								<a href="ajax/page_messages.html" class="ajax-link">
									<i class="fa fa-envelope"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle account" data-toggle="dropdown">
									<div class="avatar">
										<%= image_tag("avatar.jpg", class: "img-rounded", alt: "avatar") %>
									</div>
									<i class="fa fa-angle-down pull-right"></i>
									<div class="user-mini pull-right">
										<span class="welcome">Welcome,</span>
										<span>Jane Devoops</span>
									</div>
								</a>
								<ul class="dropdown-menu">
									<li>
										<a href="#">
											<i class="fa fa-user"></i>
											<span>Profile</span>
										</a>
									</li>
									<li>
										<a href="ajax/page_messages.html" class="ajax-link">
											<i class="fa fa-envelope"></i>
											<span>Messages</span>
										</a>
									</li>
									<li>
										<a href="ajax/gallery_simple.html" class="ajax-link">
											<i class="fa fa-picture-o"></i>
											<span>Albums</span>
										</a>
									</li>
									<li>
										<a href="ajax/calendar.html" class="ajax-link">
											<i class="fa fa-tasks"></i>
											<span>Tasks</span>
										</a>
									</li>
									<li>
										<a href="#">
											<i class="fa fa-cog"></i>
											<span>Settings</span>
										</a>
									</li>
									<li>
										<%= link_to("  Logout", destroy_user_session_path, :method=>'delete', class: "fa fa-power-off") %>
										<a href="#">
											<i class="fa fa-power-off"></i>
											<span>Logout</span>
										</a>
									</li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<!--End Header-->
<!--Start Container-->
<div id="main" class="container-fluid">
	<div class="row">
		<div id="sidebar-left" class="col-xs-2 col-sm-2">
			<ul class="nav main-menu">
				<li>
					<a href="ajax/dashboard.html" class="active ajax-link">
						<i class="fa fa-dashboard"></i>
						<span class="hidden-xs">Dashboard</span>
					</a>
				</li>
				<li><%= link_to "Περιγραφή-Εικόνα 360", ajax_dashboard_path, data: { no_turbolink: true }, class: "ajax-link fa fa-dashboard hidden-xs",remote: true %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-bar-chart-o"></i>
						<span class="hidden-xs">Charts</span>
					</a>
					<ul class="dropdown-menu">
						<li><a class="ajax-link" href="ajax/charts_xcharts.html">xCharts</a></li>
						<li><a class="ajax-link" href="ajax/charts_flot.html">Flot Charts</a></li>
						<li><a class="ajax-link" href="ajax/charts_google.html">Google Charts</a></li>
						<li><a class="ajax-link" href="ajax/charts_morris.html">Morris Charts</a></li>
						<li><a class="ajax-link" href="ajax/charts_coin k.html">CoinDesk realtime</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-table"></i>
						 <span class="hidden-xs">Tables</span>
					</a>
					<ul class="dropdown-menu">
						<li><a class="ajax-link" href="ajax/tables_simple.html">Simple Tables</a></li>
						<li><a class="ajax-link" href="ajax/tables_datatables.html">Data Tables</a></li>
						<li><a class="ajax-link" href="ajax/tables_beauty.html">Beauty Tables</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-pencil-square-o"></i>
						 <span class="hidden-xs">Forms</span>
					</a>
					<ul class="dropdown-menu">
						<li><a class="ajax-link" href="ajax/forms_elements.html">Elements</a></li>
						<li><a class="ajax-link" href="ajax/forms_layouts.html">Layouts</a></li>
						<li><a class="ajax-link" href="ajax/forms_file_uploader.html">File Uploader</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-desktop"></i>
						 <span class="hidden-xs">UI Elements</span>
					</a>
					<ul class="dropdown-menu">
						<li><a class="ajax-link" href="ajax/ui_grid.html">Grid</a></li>
						<li><a class="ajax-link" href="ajax/ui_buttons.html">Buttons</a></li>
						<li><a class="ajax-link" href="ajax/ui_progressbars.html">Progress Bars</a></li>
						<li><a class="ajax-link" href="ajax/ui_jquery-ui.html">Jquery UI</a></li>
						<li><a class="ajax-link" href="ajax/ui_icons.html">Icons</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-list"></i>
						 <span class="hidden-xs">Pages</span>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to("  Logout", destroy_user_session_path, :method=>'delete', class: "fa fa-power-off") %></li>
						<li><%= link_to("  Logout", new_user_password_path, :method=>'create', class: "fa fa-power-off") %></li>
						<li><a href="ajax/page_register.html">Register</a></li>
						<li><a id="locked-screen" class="submenu" href="ajax/page_locked.html">Locked Screen</a></li>
						<li><a class="ajax-link" href="ajax/page_contacts.html">Contacts</a></li>
						<li><a class="ajax-link" href="ajax/page_feed.html">Feed</a></li>
						<li><a class="ajax-link add-full" href="ajax/page_messages.html">Messages</a></li>
						<li><a class="ajax-link" href="ajax/page_pricing.html">Pricing</a></li>
						<li><a class="ajax-link" href="ajax/page_invoice.html">Invoice</a></li>
						<li><a class="ajax-link" href="ajax/page_search.html">Search Results</a></li>
						<li><a class="ajax-link" href="ajax/page_404.html">Error 404</a></li>
						<li><a href="ajax/page_500.html">Error 500</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-map-marker"></i>
						<span class="hidden-xs">Maps</span>
					</a>
					<ul class="dropdown-menu">
						<li><a class="ajax-link" href="ajax/maps.html">OpenStreetMap</a></li>
						<li><a class="ajax-link" href="ajax/map_fullscreen.html">Fullscreen map</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-picture-o"></i>
						 <span class="hidden-xs">Gallery</span>
					</a>
					<ul class="dropdown-menu">
						<li><a class="ajax-link" href="ajax/gallery_simple.html">Simple Gallery</a></li>
						<li><a class="ajax-link" href="ajax/gallery_flickr.html">Flickr Gallery</a></li>
					</ul>
				</li>
				<li>
					 <a class="ajax-link" href="ajax/typography.html">
						 <i class="fa fa-font"></i>
						 <span class="hidden-xs">Typography</span>
					</a>
				</li>
				 <li>
					<a class="ajax-link" href="ajax/calendar.html">
						 <i class="fa fa-calendar"></i>
						 <span class="hidden-xs">Calendar</span>
					</a>
				 </li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle">
						<i class="fa fa-picture-o"></i>
						 <span class="hidden-xs">Multilevel menu</span>
					</a>
					<ul class="dropdown-menu">
						<li><a href="#">First level menu</a></li>
						<li><a href="#">First level menu</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle">
								<i class="fa fa-plus-square"></i>
								<span class="hidden-xs">Second level menu group</span>
							</a>
							<ul class="dropdown-menu">
								<li><a href="#">Second level menu</a></li>
								<li><a href="#">Second level menu</a></li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle">
										<i class="fa fa-plus-square"></i>
										<span class="hidden-xs">Three level menu group</span>
									</a>
									<ul class="dropdown-menu">
										<li><a href="#">Three level menu</a></li>
										<li><a href="#">Three level menu</a></li>
										<li class="dropdown">
											<a href="#" class="dropdown-toggle">
												<i class="fa fa-plus-square"></i>
												<span class="hidden-xs">Four level menu group</span>
											</a>
											<ul class="dropdown-menu">
												<li><a href="#">Four level menu</a></li>
												<li><a href="#">Four level menu</a></li>
												<li class="dropdown">
													<a href="#" class="dropdown-toggle">
														<i class="fa fa-plus-square"></i>
														<span class="hidden-xs">Five level menu group</span>
													</a>
													<ul class="dropdown-menu">
														<li><a href="#">Five level menu</a></li>
														<li><a href="#">Five level menu</a></li>
														<li class="dropdown">
															<a href="#" class="dropdown-toggle">
																<i class="fa fa-plus-square"></i>
																<span class="hidden-xs">Six level menu group</span>
															</a>
															<ul class="dropdown-menu">
																<li><a href="#">Six level menu</a></li>
																<li><a href="#">Six level menu</a></li>
															</ul>
														</li>
													</ul>
												</li>
											</ul>
										</li>
										<li><a href="#">Three level menu</a></li>
									</ul>
								</li>
							</ul>
						</li>
					</ul>
				</li>
			</ul>
		</div>
		<!--Start Content-->
		<div id="content" class="col-xs-12 col-sm-10">
			<div class="preloader">
				<%= image_tag("devoops_getdata.gif", class: "devoops-getdata", alt: "preloader") %>
				
			</div>
			
			<div id="ajax-content"></div>
		</div>
		<!--End Content-->
	</div>
</div>

</body>

app/views/topologies/edit.html.erb
<h1>Editing topology</h1>

<%= render 'form' %>

<%= link_to 'Show', @topology %> |
<%= link_to 'Back', topologies_path %>

app/views/topologies/index.html.erb
<h1>Listing topologies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Topology type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @topologies.each do |topology| %>
      <tr>
        <td><%= topology.name %></td>
        <td><%= topology.topology_type %></td>
        <td><%= link_to 'Show', topology %></td>
        <td><%= link_to 'Edit', edit_topology_path(topology) %></td>
        <td><%= link_to 'Destroy', topology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topology', new_topology_path %>

app/views/topologies/new.html.erb
<h1>New topology</h1>

<%= render 'form' %>

<%= link_to 'Back', topologies_path %>

app/views/topologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @topology.name %>
</p>

<p>
  <strong>Topology type:</strong>
  <%= @topology.topology_type %>
</p>

<%= link_to 'Edit', edit_topology_path(@topology) %> |
<%= link_to 'Back', topologies_path %>